const actionTypes = {
  FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
  FETCH_BOOKS_REQUEST: 'FETCH_BOOKS_REQUEST',
  FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
  BOOKS_ADDED_TO_CART: 'BOOKS_ADDED_TO_CART',
  BOOK_REMOVES_FROM_CART: 'BOOK_REMOVES_FROM_CART',
}

export default actionTypes;
